"use client"

import type { Metadata } from "next";
import localFont from "next/font/local";
import { usePathname } from "next/navigation";
import "./globals.css";
import "./my.css"
import NavbarPage from "@/components/page/navbar.page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const Navme = () => {
  let tags: string[];
  const path = usePathname()
  tags = ["/", "/home"]
  if(path == tags[0]) {
    return console.log("hello world")
  }
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let tags: string[];
  // let Dop: (() => JSX.Element) | undefined
  const path = usePathname()
  tags = ["/", "/home"]
  // Navme()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {path == tags[0] ? <NavbarPage/> : null}
        {children}
      </body>
    </html>
  );
}
